config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'search' => 'pages#search'
  get 'translate' => 'pages#translate'
  
  get 'words' => 'words#index'
  get 'words/add' => 'words#new', as: :add_word
  post 'words/add' => 'words#create', as: :create_word
  get 'words/:id' => 'words#show', as: :show_word
  delete 'words/:id' => 'words#destroy', as: :destroy_word
  get 'words/:id/edit' => 'words#edit', as: :edit_word
  patch 'words/:id/edit' => 'words#update', as: :update_word
  
  devise_for :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :words, dependent: :destroy
  
end

app/models/word.rb
class Word < ActiveRecord::Base
  
  validates :word, presence: true, length: {maximum: 255}, uniqueness: { scope: :user_id, case_sensitive: false }
  validates :translation, presence: true, length: {maximum: 255}
  validates :definition, length: {maximum: 255}
  validates :user_id, presence: true
  
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  #before_filter :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HTTParty
  
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end

  def search
  end
  
  def translate
    response = JSON.parse HTTParty.get(
      Rails.application.secrets.yandex['uri'],
      {
        query: {
          key: Rails.application.secrets.yandex['api_key'],
          lang: "#{params['source']}-#{params['target']}",
          text: params['text']
        }
      }
    ).body
    render json: { code: response['code'], translation: response.try(:[], 'text').try(:first) }
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :get_word, :check_word_access, only: [:show, :edit, :update, :destroy]

  def new
    @word = Word.new
    @user_word = params[:w].present? ? params[:w] : ''
    @suggested_translation = params[:t].present? ? params[:t] : ''
  end

  def create
    @word = Word.new(word_params.merge({'user_id' => current_user.id}))
    if @word.save
      flash[:success] = "Added the word '#{@word.word}'"
      redirect_to add_word_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @word.update_attributes(word_params)
      flash[:success] = "Edited the word '#{@word.word}'"
      redirect_to edit_word_path(id: @word.id)
    else
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = "Deleted the word '#{@word.word}'"
      redirect_to words_path(q: params[:q], n_words: params[:n_words])
    else
      render :index
    end
  end

  def index
    @search = current_user.words.ransack(params[:q])
    @words = @search.result.order('lower(word) ASC').page(params[:page]).per(params[:n_words] || 25)
  end

  private
    def get_word
      @word = Word.find_by_id params[:id]
    end

    def check_word_access
      if !@word.present? || @word.user != current_user
        flash[:warning] = "Access denied: sorry, you don't have access to this page"
        redirect_to root_path
      end
    end

    def word_params
      params.require(:word).permit(:word, :translation, :definition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title ext
    base = "Spanglish"
    if ext.empty?
      base
    else
      "#{base} | #{ext}"
    end
  end
  
  def active_class(*actions)
    actions.include?("#{controller_name}##{action_name}") ? "active" : ""
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_footer.html.slim
footer
  .info.container-fluid
    | © 2016 Molotov Studios | Shylpx | 
    = mail_to 'shylpx@gmail.com'

app/views/layouts/_header.html.slim
#user-tools
  .btn-group
    - if user_signed_in?
      = link_to edit_user_registration_path, class: 'btn btn-info' do 
        | Edit 
        = fa_icon 'user'
      = link_to destroy_user_session_path, method: :delete, class: 'btn btn-info' do
        | Logout 
        = fa_icon 'sign-out'
    - else
      = link_to new_user_session_path, class: 'btn btn-info' do
        | Login 
        = fa_icon 'sign-in'
      = link_to new_user_registration_path, class: 'btn btn-info' do
        | Sign up 
        = fa_icon 'chevron-circle-up'
h1#logo
  = link_to 'Spanglish', root_path
.container
  - if user_signed_in?
    ul.nav.nav-tabs.nav-justified
      = content_tag :li, class: active_class('pages#search')
        = link_to search_path do
          = fa_icon 'search'
          |  Search 
      = content_tag :li, class: active_class('words#new', 'words#create')
        = link_to add_word_path do
          = fa_icon 'pencil'
          |  Add word 
      = content_tag :li, class: active_class('words#index')
        = link_to words_path do
          = fa_icon 'list'
          |  Glossary 

app/views/layouts/_word_form_fields.html.slim
.row
  .col-xs-12
    - if @word.errors.any?
      #error-explanation
        .alert.alert-danger
          ul
            - @word.errors.full_messages.each do |msg|
              li
                = msg
.row
  .col-xs-6
    .form-group class=(@word.errors.any? ? ((@word.errors.key? :word) ? 'error' : 'success') : '')
      h4
        = f.label :word do
          | Word 
          span.form-icon.glyphicon class=(@word.errors.any? ? ((@word.errors.key? :word) ? 'glyphicon-remove' : 'glyphicon-ok') : '')
      = f.text_field :word, @user_word.present? ? { class: 'form-control', value: @user_word } : { class: 'form-control' }
  .col-xs-6
    .form-group class=(@word.errors.any? ? ((@word.errors.key? :translation) ? 'error' : 'success') : '')
      h4
        = f.label :translation do
          | Translation 
          span.form-icon.glyphicon class=(@word.errors.any? ? ((@word.errors.key? :translation) ? 'glyphicon-remove' : 'glyphicon-ok') : '')
      = f.text_field :translation, @suggested_translation.present? ? { class: 'form-control', value: @suggested_translation } : { class: 'form-control' }
hr
.row
  .col-xs-12
    .form-group class=(@word.errors.any? ? ((@word.errors.key? :definition) ? 'error' : 'success') : '')
      h4
        = f.label :definition do
          | Definition 
          span.form-icon.glyphicon class=(@word.errors.any? ? ((@word.errors.key? :definition) ? 'glyphicon-remove' : 'glyphicon-ok') : '')
      = f.text_area :definition, class: 'form-control'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Josefin+Sans&subset=latin,latin-ext', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="content">
      <div class="container-fluid" id="flash">
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.slim
.container-fluid.jumbotron
  h1 Welcome to Spanglish
  p Your english-spanish glossary
  p.author by Shylpx

app/views/pages/search.html.slim
- provide :title, 'Search word'
= hidden_field_tag 'add_word_path', add_word_path
= hidden_field_tag 'translate_path', translate_path
.container-fluid
  .row
    .col-xs-6
      h4
        label Word
      input#word.form-control name='user_word' type='text' value=''
    .col-xs-6
      #result
        h4
          label Translation
        span#translated_word.form-control readonly='true'
  .row
    .col-xs-12
      h4.reference
        a href='http://translate.yandex.com/' target='_blank' Powered by Yandex.Translate
  .row
    .col-xs-12
      .actions.btn-group.pull-right
        = button_tag id: 'search_word', class: 'btn btn-info' do
          span#spinner
          | Search translation 
          = fa_icon 'search'
        = button_tag id: 'add_word', class: 'btn btn-success' do
          | Add word 
          = fa_icon 'pencil'

app/views/words/edit.html.slim
- provide :title, "Edit word"
.container-fluid
  = form_for(@word, url: update_word_path(id: @word.id)) do |f|
    = render 'layouts/word_form_fields',  f: f
    .row
      .col-xs-12
        .actions.btn-group.pull-right
          = f.button :submit, class: 'btn btn-warning' do
            | Edit word 
            = fa_icon 'edit'
          = link_to words_path, class: 'btn btn-info' do
            | Back 
            = fa_icon 'arrow-right'

app/views/words/index.html.slim
- provide :title, "Glossary"
.container-fluid
  .search-form.form-inline
    = search_form_for @search do |f|
      .form-group
        = f.search_field :word_or_translation_or_definition_cont, class: 'form-control'
      .form-group
        = number_field_tag :n_words, params[:n_words] || 25, min: 1, max: 50, class: 'form-control'
      = f.button :submit, class: 'btn btn-info' do
        | Search 
        = fa_icon 'search'
  hr
  .words-table
    - if @words.empty?
      ul
        li
          h4 There is no content to show
    - else
      table.table.table-responsive
        thead
          tr
            th Word
            th Translation
            th Definition
            th Date
        tbody
          - @words.each do |w|
            tr
              td = w.word
              td = w.translation
              td = w.definition.empty? ? "-----" : w.definition
              td = w.created_at.strftime("%-d/%-m/%Y")
              td.actions
                .action.edit-action
                  = link_to edit_word_path(id: w) do
                    = fa_icon 'edit 2x'
                .action.remove-action
                  = link_to destroy_word_path(id: w, q: params[:q], n_words: params[:n_words]), data: {confirm: "Are you sure you want to delete the word '#{w.word}'?"}, method: :delete do
                    = fa_icon 'remove 2x'
        = paginate @words, window: 2

app/views/words/new.html.slim
- provide :title, "Add new word"
.container-fluid
  = form_for(@word, url: create_word_path) do |f|
    = render 'layouts/word_form_fields',  f: f
    .row
      .col-xs-12
        .actions.btn-group.pull-right
          = f.button :submit, class: 'btn btn-success' do
            | Create word 
            = fa_icon 'pencil'

app/views/words/show.html.slim
h1 Words#show
p Find me in app/views/words/show.html.slim